# Generated by Django 3.2.3 on 2021-05-30 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('expected_salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('skill_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('full_ad_text', models.CharField(max_length=255)),
                ('candidate', models.ManyToManyField(blank=True, related_name='candidates', to='agency_app.Candidate')),
            ],
        ),
    ]
